package:
   name: numpy
   version: "2.0.0b1"

build:
  number: 0
  script: PIP_NO_INDEX= python -m pip install -vv --no-deps --ignore-installed --extra-index-url https://pypi.anaconda.org/scientific-python-nightly-wheels/simple/ --disable-pip-version-check numpy==2.0.0b1

requirements:
  host:
    - python
  run:
    - python

about:
  home: https://numpy.org/
  license: BSD
  summary: a just-in-time Python function compiler based on LLVM
